export const PRODUCTS = [
  {
    id: 1,
    name: 'Торт "Медовик"',
    price: 4500,
    weight: '1.5 кг',
    badge: 'hit',
    category: 'cake',
    venue: 'Сладкий дом',
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400&q=85',
    rating: 4.8,
    reviews: 124,
    description: 'Классический медовый торт с нежным кремом из сметаны. Тонкие медовые коржи и воздушный крем.',
  },
  {
    id: 2,
    name: 'Торт "Наполеон"',
    price: 5200,
    weight: '2 кг',
    badge: 'top',
    category: 'cake',
    venue: 'Сладкий дом',
    image: 'https://images.unsplash.com/photo-1562440499-64c9a111f713?w=400&q=85',
    rating: 4.9,
    reviews: 98,
    description: 'Слоёный торт с нежным заварным кремом. Хрустящие коржи и бархатистый крем.',
  },
  {
    id: 3,
    name: 'Шоколадный брауни',
    price: 1200,
    weight: '350 г',
    badge: 'new',
    category: 'pastry',
    venue: 'Пекарня "Уют"',
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=400&q=85',
    rating: 4.7,
    reviews: 61,
    description: 'Плотный шоколадный брауни с хрустящей корочкой и тающей серединой.',
  },
  {
    id: 4,
    name: 'Макаруны (набор 6 шт)',
    price: 2800,
    weight: '300 г',
    badge: null,
    category: 'pastry',
    venue: 'Пекарня "Уют"',
    image: 'https://images.unsplash.com/photo-1569864358642-9d1684040f43?w=400&q=85',
    rating: 4.6,
    reviews: 47,
    description: 'Французские макаруны шести вкусов. Хрустящая корочка и нежная начинка.',
  },
  {
    id: 5,
    name: 'Чизкейк "Нью-Йорк"',
    price: 3800,
    weight: '1.2 кг',
    badge: null,
    category: 'cake',
    venue: 'Кафе "Десерт"',
    image: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=400&q=85',
    rating: 4.5,
    reviews: 38,
    description: 'Нежный сливочный чизкейк на песочной основе. Классика американских кафе.',
  },
  {
    id: 6,
    name: 'Эклеры (набор 4 шт)',
    price: 1800,
    weight: '400 г',
    badge: null,
    category: 'pastry',
    venue: 'Кафе "Десерт"',
    image: 'https://images.unsplash.com/photo-1603532648955-039310d9ed75?w=400&q=85',
    rating: 4.4,
    reviews: 29,
    description: 'Классические эклеры с заварным кремом и шоколадной глазурью.',
  },
  {
    id: 7,
    name: 'Торт "Тирамису"',
    price: 5800,
    weight: '1.8 кг',
    badge: 'new',
    category: 'cake',
    venue: 'Кафе "Десерт"',
    image: 'https://images.unsplash.com/photo-1571115177098-24ec42ed204d?w=400&q=85',
    rating: 4.9,
    reviews: 18,
    description: 'Итальянский тирамису с маскарпоне и кофейной пропиткой. Без выпечки.',
  },
  {
    id: 8,
    name: 'Торт с ягодами',
    price: 6500,
    weight: '2.5 кг',
    badge: 'top',
    category: 'cake',
    venue: 'Сладкий дом',
    image: 'https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?w=400&q=85',
    rating: 4.8,
    reviews: 43,
    description: 'Нежный бисквит со свежими ягодами и сливочным кремом. Идеально для праздников.',
  },
]

export const VENUES = [
  { id: 1, name: 'Кондитерская "Сладкий дом"' },
  { id: 2, name: 'Пекарня "Уют"' },
  { id: 3, name: 'Кафе "Десерт"' },
]

export const CATEGORIES = [
  { id: 'all',     label: 'Все' },
  { id: 'cake',    label: 'Торты' },
  { id: 'pastry',  label: 'Выпечка' },
]

export const CHEFS = [
  {
    id: 1,
    name: 'Айгуль Н.',
    venue: 'Сладкий дом',
    specialty: 'Свадебные торты',
    orders: 234,
    rating: 4.9,
    years: 8,
    initials: 'АН',
    gradient: 'linear-gradient(135deg, #e8698a, #c94a6a)',
  },
  {
    id: 2,
    name: 'Самал К.',
    venue: 'Пекарня "Уют"',
    specialty: 'Французская выпечка',
    orders: 187,
    rating: 4.8,
    years: 5,
    initials: 'СК',
    gradient: 'linear-gradient(135deg, #c9a96e, #8a6530)',
  },
  {
    id: 3,
    name: 'Гульнар М.',
    venue: 'Кафе "Десерт"',
    specialty: 'Муссовые торты',
    orders: 312,
    rating: 4.9,
    years: 10,
    initials: 'ГМ',
    gradient: 'linear-gradient(135deg, #a78bfa, #7c3aed)',
  },
  {
    id: 4,
    name: 'Роза Б.',
    venue: 'Atelier de Sucre',
    specialty: 'Шоколадные десерты',
    orders: 156,
    rating: 4.7,
    years: 4,
    initials: 'РБ',
    gradient: 'linear-gradient(135deg, #f9a8d4, #db2777)',
  },
  {
    id: 5,
    name: 'Дина О.',
    venue: 'Cacao & Bloom',
    specialty: 'Торты без глютена',
    orders: 98,
    rating: 4.8,
    years: 3,
    initials: 'ДО',
    gradient: 'linear-gradient(135deg, #6ee7b7, #059669)',
  },
]

export const REVIEWS = [
  {
    id: 1,
    name: 'Алия Бекова',
    initials: 'АБ',
    gradient: 'linear-gradient(135deg, #fce8ed, #f5d0de)',
    textColor: '#e8698a',
    rating: 5,
    date: '12 мая 2025',
    text: 'Заказывала медовик на день рождения мужа. Доставили вовремя, торт был просто восхитительный! Все гости были в полном восторге. Буду заказывать снова.',
    product: 'Торт "Медовик"',
  },
  {
    id: 2,
    name: 'Майра Нурова',
    initials: 'МН',
    gradient: 'linear-gradient(135deg, #dbeafe, #bfdbfe)',
    textColor: '#2563eb',
    rating: 5,
    date: '8 мая 2025',
    text: 'Наполеон — это что-то невероятное. Нежнейший крем, хрустящие коржи. Именно такой торт я ела в детстве у бабушки. Спасибо кондитеру!',
    product: 'Торт "Наполеон"',
  },
  {
    id: 3,
    name: 'Дана Сейткали',
    initials: 'ДС',
    gradient: 'linear-gradient(135deg, #dcfce7, #bbf7d0)',
    textColor: '#16a34a',
    rating: 5,
    date: '3 мая 2025',
    text: 'Удобный сервис! Выбрала торт, оформила заказ — через час уже на столе. Макаруны тают во рту. Упаковка красивая, всё пришло целым.',
    product: 'Макаруны (набор 6 шт)',
  },
]

export const GALLERY = [
  { id: 1, src: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&q=85', alt: 'Медовик' },
  { id: 2, src: 'https://images.unsplash.com/photo-1562440499-64c9a111f713?w=600&q=85', alt: 'Наполеон' },
  { id: 3, src: 'https://images.unsplash.com/photo-1586985289688-ca3cf47d3e6e?w=600&q=85', alt: 'Торт с розами' },
  { id: 4, src: 'https://images.unsplash.com/photo-1569864358642-9d1684040f43?w=600&q=85', alt: 'Макаруны' },
  { id: 5, src: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=600&q=85', alt: 'Чизкейк' },
  { id: 6, src: 'https://images.unsplash.com/photo-1603532648955-039310d9ed75?w=600&q=85', alt: 'Эклеры' },
]

export const CONSTRUCTOR_OPTIONS = {
  bases: [
    { id: 'biscuit',   label: 'Бисквит',        price: 0 },
    { id: 'honey',     label: 'Медовый',         price: 300 },
    { id: 'napoleon',  label: 'Слоёный',         price: 500 },
    { id: 'chocolate', label: 'Шоколадный',      price: 400 },
  ],
  fillings: [
    { id: 'cream',      label: 'Сливочный крем',    price: 0 },
    { id: 'chocolate',  label: 'Шоколадный крем',   price: 300 },
    { id: 'fruit',      label: 'Фруктовый джем',    price: 400 },
    { id: 'condensed',  label: 'Варёная сгущёнка',  price: 200 },
  ],
  sizes: [
    { id: 'small',  label: '1 кг (до 6 чел)',   price: 3000 },
    { id: 'medium', label: '2 кг (до 12 чел)',  price: 5500 },
    { id: 'large',  label: '3 кг (до 20 чел)',  price: 8000 },
  ],
  shapes: [
    { id: 'round',  label: 'Круглый',    price: 0 },
    { id: 'square', label: 'Квадратный', price: 200 },
    { id: 'heart',  label: 'Сердце',     price: 500 },
  ],
  decorations: [
    { id: 'none',    label: 'Без декора',         price: 0 },
    { id: 'flowers', label: 'Цветы из крема',      price: 800 },
    { id: 'berries', label: 'Свежие ягоды',        price: 1200 },
    { id: 'figures', label: 'Сахарные фигурки',    price: 600 },
  ],
  extras: [
    { id: 'candles',   label: 'Свечи',                price: 200 },
    { id: 'sparklers', label: 'Бенгальские огни',     price: 300 },
    { id: 'topper',    label: 'Топпер',               price: 500 },
    { id: 'box',       label: 'Подарочная коробка',   price: 400 },
  ],
}

export const ORDER_STATUSES = {
  bidding:   { label: 'Приём ставок',           color: 'text-purple-600 bg-purple-50' },
  pending:   { label: 'Ожидает подтверждения',  color: 'text-yellow-600 bg-yellow-50' },
  confirmed: { label: 'Подтверждён',            color: 'text-blue-600 bg-blue-50' },
  preparing: { label: 'Готовится',              color: 'text-orange-600 bg-orange-50' },
  ready:     { label: 'Готов',                  color: 'text-green-600 bg-green-50' },
  delivered: { label: 'Доставлен',              color: 'text-gray-600 bg-gray-100' },
  cancelled: { label: 'Отменён',                color: 'text-red-600 bg-red-50' },
}
